create database hpcf1;
use hpcf1;
CREATE TABLE Customer
(
  C_Name VARCHAR(20) NOT NULL,
  C_ID VARCHAR(20) NOT NULL,
  C_Address VARCHAR(50) NOT NULL,
  C_Mobile VARCHAR(20) NOT NULL,
  PRIMARY KEY (C_ID)
);

CREATE TABLE Site
(
  Site_Name VARCHAR(20) NOT NULL,
  S_Status VARCHAR(20) NOT NULL,
  S_Desc VARCHAR(20) NOT NULL,
  PRIMARY KEY (Site_Name)
);

CREATE TABLE Hotel
(
  Hotel_ID VARCHAR(20) NOT NULL,
  Hotel_Name VARCHAR(20) NOT NULL,
  Hotel_Desc VARCHAR(20) NOT NULL,
  Total_Rooms VARCHAR(20) NOT NULL,
  PRIMARY KEY (Hotel_ID)
);

CREATE TABLE Locations
(
  Street VARCHAR(20) NOT NULL,
  Locality VARCHAR(20) NOT NULL,
  City VARCHAR(20) NOT NULL,
  Plot_No VARCHAR(20) NOT NULL,
  Hotel_ID VARCHAR(20) NOT NULL,
  PRIMARY KEY (Plot_No),
  FOREIGN KEY (Hotel_ID) REFERENCES Hotel(Hotel_ID)
);

CREATE TABLE Facilities
(
  F_ID VARCHAR(20) NOT NULL,
  F_Name VARCHAR(20) NOT NULL,
  F_Desc VARCHAR(20) NOT NULL,
  Hotel_ID VARCHAR(20) NOT NULL,
  PRIMARY KEY (F_ID),
  FOREIGN KEY (Hotel_ID) REFERENCES Hotel(Hotel_ID)
);

CREATE TABLE Guide
(
  Guide_ID INT NOT NULL,
  Guide_Name VARCHAR(20) NOT NULL,
  Guide_Mobile VARCHAR(20) NOT NULL,
  PRIMARY KEY (Guide_ID)
);

CREATE TABLE Room
(
  Room_ID VARCHAR(20) NOT NULL,
  Room_Type VARCHAR(20) NOT NULL,
  Capacity VARCHAR(20) NOT NULL,
  R_Status VARCHAR(20) NOT NULL,
  Hotel_ID VARCHAR(20) NOT NULL,
  PRIMARY KEY (Room_ID),
  FOREIGN KEY (Hotel_ID) REFERENCES Hotel(Hotel_ID)
);

CREATE TABLE Price
(
  Price VARCHAR(20) NOT NULL,
  Room_ID VARCHAR(20) NOT NULL,
  Hotel_ID VARCHAR(20) NOT NULL,
  PRIMARY KEY (Room_ID, Hotel_ID),
  FOREIGN KEY (Room_ID) REFERENCES Room(Room_ID),
  FOREIGN KEY (Hotel_ID) REFERENCES Hotel(Hotel_ID)
);

CREATE TABLE Bill
(
  Bill_No VARCHAR(20) NOT NULL,
  No_Of_Rooms VARCHAR(20) NOT NULL,
  Total_Amount VARCHAR(20) NOT NULL,
  C_ID VARCHAR(20) NOT NULL,
  Room_ID VARCHAR(20) NOT NULL,
  PRIMARY KEY (Bill_No),
  FOREIGN KEY (C_ID) REFERENCES Customer(C_ID),
  FOREIGN KEY (Room_ID) REFERENCES Room(Room_ID)
);

CREATE TABLE Reservation
(
  Res_ID VARCHAR(20) NOT NULL,
  Cin_Date DATE NOT NULL,
  Cout_Date DATE NOT NULL,
  Res_Status VARCHAR(50) NOT NULL,
  C_ID VARCHAR(20) NOT NULL,
  Room_ID VARCHAR(20) NOT NULL,
  PRIMARY KEY (Res_ID),
  FOREIGN KEY (C_ID) REFERENCES Customer(C_ID),
  FOREIGN KEY (Room_ID) REFERENCES Room(Room_ID)
);

